spring.application.name=chat-app

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/chat_app
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# File upload - 100 MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Static resources
spring.web.resources.static-locations=classpath:/static/

# Disable default login page/security generated password
spring.jpa.open-in-view=false